name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run pre-commit
        uses: nikaro/actions/pre-commit@0705e6833c832dff631da68d70747cabbb00048d # 0.7.6

  test:
    name: Test
    needs: [lint]
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install pre-commit
        run: pipx install pre-commit

      - name: Try pre-commit
        run: pre-commit try-repo --verbose --all-files .
