name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Run pre-commit
        uses: nikaro/actions/pre-commit@89504f15e51cfdb0ca91e07bad599eca5b861a7d # 1.3.22

  test:
    name: Test
    needs: [lint]
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Install pre-commit
        run: pipx install pre-commit

      - name: Try pre-commit
        run: pre-commit try-repo --verbose --all-files .
