name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Run pre-commit
        uses: nikaro/actions/pre-commit@e77a13149bd439f1dce6e1ab7eee379855f71a0e # 1.6.1

  test:
    name: Test
    needs: [lint]
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Install pre-commit
        run: pipx install pre-commit

      - name: Try pre-commit
        run: pre-commit try-repo --verbose --all-files .
