name: Release

on:
  push:
    branches: [main]
    paths-ignore:
      - .github/**
      - .cz.toml
      - .gitignore
      - .pre-commit-config.yaml
      - .yamllint.yml
      - CHANGELOG.md
  workflow_dispatch:

env:
  # renovate: datasource=pypi depName=commitizen
  COMMITIZEN_VERSION: 3.14.1

jobs:
  release:
    name: Release
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@595dabb3acf442d47e29c9ec9ba44db0c6bdd18f # v1.3.3
        with:
          check-name: Test
          ref: ${{ github.ref }}
          repo-token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Dry run
        uses: commitizen-tools/commitizen-action@bc2616fec6b3effc9ad20380f19550a8b18cdbdf # 0.20.0
        with:
          github_token: ${{ github.token }}
          changelog_increment_filename: _changelog.md
          commitizen_version: ${{ env.COMMITIZEN_VERSION }}
          dry_run: true

      - name: Bump
        uses: commitizen-tools/commitizen-action@bc2616fec6b3effc9ad20380f19550a8b18cdbdf # 0.20.0
        with:
          github_token: ${{ github.token }}
          changelog_increment_filename: _changelog.md
          commitizen_version: ${{ env.COMMITIZEN_VERSION }}

      - name: Release
        uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5 # v1.13.0
        with:
          bodyFile: _changelog.md
          skipIfReleaseExists: true
          tag: ${{ env.REVISION }}
